### ISSUE TITLE
pyproj.exceptions.CRSError

### ISSUE THREAD

**Issue by cc863** [iamdonovan/spymicmac#38]
hello
I encountered the following issues while running register_ortho.py

start.
No date information read from filename.
Traceback (most recent call last):
  File "/media/rs/5AA23466A23448B11/例子/register_ortho.py", line 55, in <module>
    main()
  File "/media/rs/5AA23466A23448B11/例子/register_ortho.py", line 41, in main
    register_ortho(args.fn_ortho, args.fn_ref, args.fn_reldem, args.fn_dem,
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/spymicmac/register.py", line 330, in register_ortho
    mask_full, _, ref_img = get_mask(footprints, ref_img, imlist, landmask, glacmask)
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/spymicmac/register.py", line 244, in get_mask
    fmask, fprint = get_footprint_mask(footprints, img, imlist, fprint_out=True)
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/spymicmac/register.py", line 211, in get_footprint_mask
    fprint = get_footprint_overlap(fp.to_crs(geoimg.proj4))
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1364, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/geopandas/geoseries.py", line 1124, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/geopandas/array.py", line 767, in to_crs
    crs = CRS.from_user_input(crs)
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/pyproj/crs/crs.py", line 501, in from_user_input
    return cls(value, **kwargs)
  File "/home/rs/anaconda3/envs/spymicmac/lib/python3.10/site-packages/pyproj/crs/crs.py", line 348, in __init__
    self._local.crs = _CRS(self.srs)
  File "pyproj/_crs.pyx", line 2366, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: : (Internal Proj Error: proj_create: unrecognized format / unknown name)

**Comment by iamdonovan** [comment]
What is the output of `gdalinfo` of the file that you are using for the reference image (`ref_img`)?

**Comment by cc863** [comment]
The files used for reference are Landsat. tif and DEM. tif, and no results were output until the error was reported

> What is the output of of the file that you are using for the reference image ()?`gdalinfo``ref_img`

**Comment by iamdonovan** [comment]
Can you run the following commands in the terminal?

> `gdalinfo Landsat.tif`

> `gdalinfo DEM.tif`

and then paste/upload a screenshot of the output?

**Comment by cc863** [comment]
gdalinfo Landsat.tif
![e2dde670e61eafb96c5ed773467524c1](https://github.com/iamdonovan/spymicmac/assets/100006248/dfa5acd2-5a0e-4f1f-9ee3-5787bffe9c85)
gdalinfo DEM.tif
![560912e2d4aaa58e090914178bd3844d](https://github.com/iamdonovan/spymicmac/assets/100006248/4f83fa78-5a9d-4cff-828d-2451799e6dee)
![a8a31f4d96c2d4c9126eee7d43130dac](https://github.com/iamdonovan/spymicmac/assets/100006248/01107ca3-96c5-4047-973d-e00b4d7d038c)

**Comment by iamdonovan** [comment]
That's the problem - `Landsat.tif` is not georeferenced, and so has no valid CRS. You need to make sure that this image is georeferenced to a projected (not geodetic) coordinate system like UTM.

**Comment by cc863** [comment]
thank you very much!May I ask if the row and column numbers of Dem. tif and Landsat. tif need to be consistent? I have encountered the following problem
![dc16e18fdc78d18a57a5681d3374d057](https://github.com/iamdonovan/spymicmac/assets/100006248/698e7e83-7afd-4cdd-9c43-982e30c47682)

**Comment by iamdonovan** [comment]
Your Landsat image has 3 bands - select a single band (for example, the panchromatic band) to use here.

**Comment by cc863** [comment]
Thank you very much! ！！Sorry，perhaps my data is still not quite correct, and I need to ask for your guidance again
![4a49b878819e529fc7c22b82d19f1a19](https://github.com/iamdonovan/spymicmac/assets/100006248/bd297971-fb01-470d-b335-3f30310e47cc)
